function genMainPage(lista,data,title){
    var pagHTML = `
        <DOCTYPE html>
            <head>
                <meta charset"UTF-8"/>
                <title> ${title} </title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">

                <header class="w3-container w3-blue w3-center">
                <h1>Lista de pessoas na Base de Dados (${lista.length})</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all w3-centered w3-hoverable w3-large">
                    <tr>
                        <th> Id </th>
                        <th> Nome </th>
                        <th> Idade </th>
                        <th> Sexo </th>
                        <th> Cidade </th>
                    </tr>`

    for(let i=0;i<lista.length;i++)
    {
        pagHTML += `
                    <tr>
                        <td> ${lista[i].id} </td>
                        <td> 
                            <a href="http://localhost:7777/pessoas/${lista[i].id}">${lista[i].nome}</a> 
                        </td> 
                        <td> ${lista[i].idade} </td>
                        <td> ${lista[i].sexo} </td>
                        <td> ${lista[i].morada.cidade} </td>
                    </tr>
        `
    }

    pagHTML += `
                </table>
            </div>

            <footer class="w3-container w3-blue w3-center">
              <h5>Generated by pessoas-server: ${data}</h5>
              <h4><a href="http://localhost:7777/">Voltar ao Menu</a><h4>
            </footer>

            </div>
        </body>
    </html>
    `

    return pagHTML;
}

exports.genMainPage = genMainPage;


exports.genPersonPage = function(p,d){
    var pagHTML = `
        <DOCTYPE html>
            <head>
                <meta charset="UTF-8"/>
                <title> Person Page </title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-blue w3-center">
                        <h1>Nome: ${p.nome}</h1>
                    </header>

                    <div class="w3-container">
                        <table class="w3-table-all w3-centered w3-hoverable w3-large"> 
                            <tr>
                                <th>Idade: ${p.idade}</th>
                                <th>Sexo: ${p.sexo} </th>
                            </tr>
                            <tr> 
                                <th> Cidade: ${p.morada.cidade} </th>
                                <th> Distrito: ${p.morada.distrito} </th>
                            </tr>
                            <tr> 
                                <th> BI: ${p.BI} </th>
                                <th> Profissão: ${p.profissao} </th>
                            </tr>
                            <tr> 
                                <th> Partido Político: ${p.partido_politico.party_name} (${p.partido_politico.party_abbr}) </th>
                                <th> Religiao: ${p.religiao} </th>
                            </tr>
                            <tr> 
                                <th> Desportos: ${p.desportos} </th>
                                <th> Animais: ${p.animais} </th>
                            </tr>
                            <tr> 
                                <th> Figura Publica: ${p.figura_publica_pt} </th>
                                <th> Marca Carro: ${p.marca_carro} </th>
                            </tr>
                        </table>
                    
                    <header class="w3-container w3-blue w3-center">
                        <h3>Atributos</h1>
                    </header>
                    <table class="w3-table-all w3-hoverable"> 
        `
    var arrayNames = ["Fumador","Gosta de Cinema","Gosta de viajar","Acorda cedo", "Gosta de ler", "Gosta de musica", "Gosta de comer", "Gosta de cinema", "Gosta de animais de estimacao", "Gosta de dancar", "Comida favorita"]
    var array = ["fumador","gosta_cinema","gosta_viajar","acorda_cedo", "gosta_ler", "gosta_musica", "gosta_comer", "gosta_cinema", "gosta_animais_estimacao", "gosta_dancar", "comida_favorita"]
    for(i=0;i<9;i++)
    {
        var sArray = array[i]
        pagHTML += ` <tr> <th> ${arrayNames[i]} </th> `
        if(p.atributos[sArray] === true)
            pagHTML += `<td>&check;</td>`
        else pagHTML += `<td>&times;</td>`
        pagHTML += `</tr>`
    }

    pagHTML += `
                    </table>
                    <footer class="w3-container w3-blue w3-center">
                        <h4><a href="http://localhost:7777/">Voltar ao Menu</a></h4>
                    </footer>
                </div>
            </body>
        </html>
    `

    return pagHTML;
}

function calculateDistribution(lista,parameter)
{
    const myDict = {}
    for(let i=0;i<lista.length;i++)
    {
        if (lista[i][parameter] in myDict)
            myDict[lista[i][parameter]] += 1;
        else myDict[lista[i][parameter]]=1;
    }

    for (let key in myDict) 
        myDict[key] = ((myDict[key] / lista.length) * 100).toFixed(2);
    
    const sortedEntries = Object.entries(myDict).sort((a, b) => b[1] - a[1]);
    const sortedDict = {};
    sortedEntries.forEach(entry => {sortedDict[entry[0]] = entry[1];});
    return sortedDict;
}

function calculateDistributions(lista,parameter)
{
    const myDict = {}
    for(let i=0;i<lista.length;i++)
    {
        for(let j=0;j<lista[i][parameter].length;j++)
        {
            if (lista[i][parameter][j] in myDict)
                myDict[lista[i][parameter][j]] += 1;
            else myDict[lista[i][parameter][j]]=1;
        }
        
    }
    for (let key in myDict) 
        myDict[key] = ((myDict[key] / lista.length) * 100).toFixed(2);
    
    const sortedEntries = Object.entries(myDict).sort((a, b) => b[1] - a[1]);
    const sortedDict = {};
    sortedEntries.forEach(entry => {sortedDict[entry[0]] = entry[1];});
    return sortedDict;
}

function calculateDistributionsList(lista,parameter,key)
{
    const res = []
    let keyP = key.replace(/%20/g, " ")
    for(let i=0;i<lista.length;i++)
    {
        if (lista[i][parameter].includes(keyP))
            res.push(lista[i]);
    }
    return res;
}

function calculateDistributionList(lista,parameter,key)
{
    const res = []
    for(let i=0;i<lista.length;i++)
    {
        if (lista[i][parameter] === key)
            res.push(lista[i]);
    }
    return res;
}



exports.genDistOptionPage = function(p,d,option,i){
    var pagHTML = `
        <DOCTYPE html>
        <head>
            <meta charset="UTF-8"/>
            <title>  Index Page </title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue w3-center">
                    <h1>Distribuição de ${option}</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable w3-large"> 
    `
    var myDict = calculateDistribution(p,option);
    if(i==0) myDict = Object.fromEntries(Object.entries(myDict).slice(0, 10));
    for (let key in myDict) 
    {
        pagHTML += `<tr>
                        <th><a href="http://localhost:7777/pessoas/distribuicao/${option}/${key}">${key}</th>
                        <td>${myDict[key]}%</td>
                    </tr>`
    }

    pagHTML += `
                </table>
                </div>
                <footer class="w3-container w3-blue w3-center">
                    <h4><a href="http://localhost:7777/">Voltar ao Menu</a></h4>
                </footer>
                </div>
            </body>
        </html>
    `

    

    return pagHTML;
}



exports.genDistOptionsPage = function(p,d,option,i){
    var pagHTML = `
        <DOCTYPE html>
            <head>
                <meta charset"UTF-8"/>
                <title class="w3-container w3-blue w3-center"> Distribution by ${option} </title>
            </head>
            <body>
                <table class="w3-table-all w3-centered w3-hoverable w3-large"> 
    `
    var myDict = calculateDistributions(p,option);

    if(i==0) myDict = Object.fromEntries(Object.entries(myDict).slice(0, 10));

    for (let key in myDict) 
    {
        
        pagHTML += `<tr>
                        <th><a href="http://localhost:7777/pessoas/distribuicao/${option}/${key}">${key}</th>
                        <td>${myDict[key]}%</td>
                    </tr>`
    }

    pagHTML += `
                </table>
            </body>
        </html>
    `

    

    return pagHTML;
}



exports.genDistOptionXPage = function(p,d,option,k,i){
    const res = calculateDistributionList(p,option,k);
    if (i == 0)
        res = res.slice(0,10)
    return genMainPage(res,d,"Distribuição " + option + " " + k);
}

exports.genDistOptionsXPage = function(p,d,option,k,i){
    const res = calculateDistributionsList(p,option,k);
    if (i == 0)
        res = res.slice(0,10)
    return genMainPage(res,d,"Distribuição " + option + " " + k);
}

exports.indexPage = function()
{
    var pagHTML = `
        <DOCTYPE html>
            <head>
                <meta charset="UTF-8"/>
                <title>  Index Page </title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">

                    <header class="w3-container w3-blue w3-center">
                        <h1>Indice</h1>
                    </header>

                    <div class="w3-container">
                        <table class="w3-table-all w3-centered w3-hoverable w3-large"> 
                            <tr>
                                <th><a href="http://localhost:7777/pessoas">Lista de Pessoas</a> </th>
                            </tr>
                            <tr>
                                <th><a href="http://localhost:7777/pessoasOrdenadas">Lista de Pessoas Ordenadas</a> </th>
                            </tr>
                            <tr> 
                                <th><a href="http://localhost:7777/pessoas/distribuicao">Distribuições</a> </th>
                            </tr>
                            <tr> 
                                <th><a href="http://localhost:7777/pessoas/top10">Top 10</a> </th>
                            </tr>
                        </table>
                    </div>
                
                    <footer class="w3-container w3-blue w3-center">
                        <h4><a href="http://localhost:7777/">Voltar ao Menu</a></h4>
                    </footer>
                </div>
            </body>
        </html>
    `
    return pagHTML;
}


exports.indexDistribuicoes = function()
{
    var pagHTML = `
        <DOCTYPE html>
            <head>
                <meta charset="UTF-8"/>
                <title>  Distributions Page </title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-blue w3-center">
                        <h1>Indice de Distribuição</h1>
                    </header>

                    <div class="w3-container">
                        <table class="w3-table-all w3-centered w3-hoverable w3-large"> 
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/distribuicao/nome">Distribuição por Nome</td>
                            </tr>
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/distribuicao/idade">Distribuição por Idade</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/distribuicao/sexo">Distribuição por Sexo</td>
                            </tr>
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/distribuicao/profissao">Distribuição por Profissao</td>
                            </tr>
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/distribuicao/religiao">Distribuição por Religião</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/distribuicao/desportos">Distribuição por Desportos</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/distribuicao/animais">Distribuição por Animais</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/distribuicao/figura_publica_pt">Distribuição por Figuras Publicas Portuguesas</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/distribuicao/marca_carro">Distribuição por Marca de Carro</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/distribuicao/destinos_favoritos">Distribuição por Destinos favoritos</td>
                            </ </div>tr>
                        </table>
                    </div>
                    <footer class="w3-container w3-blue w3-center">
                        <h4><a href="http://localhost:7777/">Voltar ao Menu</a></h4>
                    </footer>
                </div>
            </body>
        </html>
    `
    return pagHTML;
}


exports.indexTop10 = function()
{
    var pagHTML = `
        <DOCTYPE html>
            <head>
                <meta charset="UTF-8"/>
                <title>  Top 10 Page </title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-blue w3-center">
                        <h1>Indice Top 10</h1>
                    </header>

                    <div class="w3-container">
                        <table class="w3-table-all w3-centered w3-hoverable w3-large"> 
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/top10/nome">Distribuição por Nome</td>
                            </tr>
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/top10/idade">Distribuição por Idade</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/top10/sexo">Distribuição por Sexo</td>
                            </tr>
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/top10/profissao">Distribuição por Profissao</td>
                            </tr>
                            <tr>
                                <td><a href="http://localhost:7777/pessoas/top10/religiao">Distribuição por Religião</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/top10/desportos">Distribuição por Desportos</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/top10/animais">Distribuição por Animais</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/top10/figura_publica_pt">Distribuição por Figuras Publicas Portuguesas</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/top10/marca_carro">Distribuição por Marca de Carro</td>
                            </tr>
                            <tr> 
                                <td><a href="http://localhost:7777/pessoas/top10/destinos_favoritos">Distribuição por Destinos favoritos</td>
                            </tr>
                        </table>
                    </div>
                    <footer class="w3-container w3-blue w3-center">
                        <h4><a href="http://localhost:7777/">Voltar ao Menu</a></h4>
                    </footer>
                </div>
            </body>
        </html>
    `
    return pagHTML;
}